# Generated by Django 5.2.8 on 2025-11-13 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('menu', models.CharField(max_length=100)),
                ('pedidos', models.CharField(max_length=100)),
                ('cocina', models.CharField(max_length=100)),
                ('reservas', models.CharField(max_length=100)),
            ],
        ),
    ]
