# Generated by Django 5.2.8 on 2025-11-13 05:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Comida',
            new_name='Restaurante',
        ),
    ]
